import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { CustomerProvider } from "@/components/providers/CustomerContext";
import { ItemProvider } from "@/components/providers/ItemContext";
import { InvoiceProvider } from "@/components/providers/InvoiceContext";
import { ProjectProvider } from "@/components/providers/ProjectContext";
import { AuthProvider } from "@/components/providers/AuthContext";
import { LayoutWrapper } from "@/components/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-slate-900 bg-white`}
      >
        <AuthProvider>
          <CustomerProvider>
            <ItemProvider>
              <InvoiceProvider>
                <ProjectProvider>
                  <LayoutWrapper>{children}</LayoutWrapper>
                </ProjectProvider>
              </InvoiceProvider>
            </ItemProvider>
          </CustomerProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
